<div class="frontmatter text-center">
<h1> Introduction to Data Science and Programming</h1>
<h2>Exercise 11: Array programming with numpy</h2>
<h3>IT University of Copenhagen, Fall 2023</h3>
</div>

NumPy is a python library used for working with (large) n-dimensional arrays. It can be used as you would Excel, operating quickly on rows and columns -- even when your amount of data is **MASSIVE** and would crash your computer if you tried to open it in Excel.

It even has functions for working in the domains of linear algebra and matrix operations!

In [2]:
import numpy as np

## Creating and reshaping arrays

### 11. 1. Create a one dimensional array of length 10 filled with integer zeros
Hint: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

```[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]```

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0.])

### 11.2. Create a two dimensional array of size 3x5 filled with floating point ones
Hint: https://numpy.org/doc/stable/reference/generated/numpy.ones.html

```[[1., 1., 1., 1., 1.],
  [1., 1., 1., 1., 1.],
  [1., 1., 1., 1., 1.]]```

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 11.3. Create a two dimensional array of size 3x5 filled with the float 3.14
Hint: https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full

```[[3.14, 3.14, 3.14, 3.14, 3.14],
  [3.14, 3.14, 3.14, 3.14, 3.14],
  [3.14, 3.14, 3.14, 3.14, 3.14]]```

In [7]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### 11.4. Create a 3x3 identity matrix
Hint: https://numpy.org/doc/stable/reference/generated/numpy.identity.html

```[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]```

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 11.5. Create a one dimensional array with 9 elements using numpy's range generator to fill the array with the values 1-9.
Hint: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

```[1, 2, 3, 4, 5, 6, 7, 8, 9]```

**!** Save the array under the variable ```A```

In [11]:
A = np.arange(1,10)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 11.6. Create a two dimensional array of size 3x3 by reshaping the array A
Hint: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

```[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]```

**!** Save the array under the variable ``B``

In [33]:
B = np.reshape(A,(3,3))
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 11.7. Create a two dimensional array of size 3x3 using numpy's random integer generator to fill the values in the array with numbers n, $0 \leq n \leq 10$

Hint: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

```[[6, 5, 9],
  [0, 6, 3],
  [6, 4, 2]]```

Example output -- remember the actual numbers $0 \leq n \leq 10$ will be random

**!** Save the array under the variable ``C``

In [19]:
C = np.random.randint(10,size = (3,3))
C

array([[6, 1, 9],
       [1, 2, 1],
       [4, 8, 2]])

### 11.8. Create a three dimensional array of size 4x3x3 using numpy's random number generator to  fill the values in the array
Hint: https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html

```[[[8.47479123e-04, 6.77383718e-01, 4.85670390e-01],
   [4.83278589e-01, 6.15245314e-01, 2.11490849e-01],
   [1.49347953e-01, 7.83983365e-01, 5.53822889e-01]],
  [[3.04016610e-01, 6.25469077e-01, 6.48571722e-01],
   [8.63629619e-01, 3.12534574e-01, 3.18482080e-01],
   [4.55083532e-01, 9.85150456e-01, 4.84004643e-01]],
  [[3.43469344e-01, 5.43381121e-01, 2.49079720e-01],
   [6.04169755e-01, 5.95389658e-01, 5.19062476e-01],
   [7.49293335e-01, 5.31758774e-01, 5.41012678e-01]],
  [[4.55190187e-03, 4.95023710e-01, 9.22839467e-01],
   [9.11154749e-01, 8.65357016e-01, 4.74276473e-01],
   [2.86203208e-01, 4.75279571e-01, 7.51917714e-02]]] ```

Example output -- remember the actual numbers $0 \leq n < 1$ will be random

In [27]:
D = np.random.rand(4,3,3)
D

array([[[0.48336626, 0.58048565, 0.19751082],
        [0.86059303, 0.34236318, 0.58826899],
        [0.73537923, 0.55641361, 0.35161201]],

       [[0.64521127, 0.53324269, 0.62189673],
        [0.02955568, 0.61726013, 0.01629359],
        [0.40453063, 0.83052762, 0.93528754]],

       [[0.60599401, 0.15810566, 0.84300271],
        [0.36857437, 0.7183333 , 0.15082846],
        [0.66574476, 0.22647668, 0.16698496]],

       [[0.28160855, 0.81445442, 0.87308132],
        [0.24300131, 0.18347143, 0.93961548],
        [0.54404288, 0.42611286, 0.56533792]]])

<font size = 4, color=green>*Do you see the pattern with dimensions and output format?*</font>

## Indexing and slicing arrays

Hints: https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

### 11.9. From the one dimensional array, A, print elements from the index 2 to 4 using the array slice operations

```[3, 4, 5]```

In [108]:
A[2:5]    

[1 2 3]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 11.10. From the two dimensional array, B, print the value of the 3rd element in the 2nd row using array indexing

```6```

In [116]:
print(B[1,2])
print(B[1][2])

#Another way to look at it
for idxi,i in enumerate(B):
    if(idxi == 1):        
        for idxj,j in enumerate(i):
            if( idxj == 2):
                print(j)



6
6
6


array([[1, 2],
       [4, 5],
       [7, 8]])

### 11.11. From the two dimensional array, B, print the first two elements of each row using array slicing
```[[1, 2],
 [4, 5],
 [7, 8]]```

In [45]:
B[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### 11.12. Create a one dimensional null vector of size 10 and update first the 5th and then the 7th value to be 42 using array indexing

Extra hint: exercise 11.1

```[ 0.,  0.,  0.,  0., 42.,  0., 42.,  0.,  0.,  0.]```

**!** Save the array under the variable ``D``

In [48]:
D = np.zeros(10)
D[4] = 42
D[6] = 42
D

array([ 0.,  0.,  0.,  0., 42.,  0., 42.,  0.,  0.,  0.])

## Working with arrays

### 11.13. Find indices of non-zero elements from the array D
Hint: https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html

```(array([4, 6]),)```

In [50]:
D.nonzero()

(array([4, 6], dtype=int64),)

### 11.14. Find the overall minimum and maximum values of the array B

Hints: 
- https://numpy.org/doc/stable/reference/generated/numpy.amin.html
- https://numpy.org/doc/stable/reference/generated/numpy.amax.html

Min: ```1```
Max: ```9```

In [55]:
print(B.min())
print(B.max())

9

### 11.15 Find the minimum and maximum values in each row of the array B
Hint: same as 11.4, but with axis

Min: ```[1 4 7]```
Max: ```[3 6 9]```

In [145]:
##print(B.min(1))
##print(B.max(1))

tester = np.array([[2,2,5],[2,3,1],[7,8,9],[7,8,9]])

tester.min(0)

#np.amin(tester,0)

array([2, 2, 1])

### 11.15 Find the maximum and minimum values in each column of the array B
Hint: same as 11.4, but with axis

Min: ```[1 2 3]```
Max: ```[7 8 9]```

In [62]:
print(B.min(0))
print(B.max(0))

[1 2 3]
[7 8 9]


### 11.16 Find the mean value of the whole array B
Hint: https://numpy.org/doc/stable/reference/generated/numpy.mean.html

```5.0```

In [63]:
B.mean()

5.0

### 11.17. Check if any of the elements in the arrays B and C are equal
Hint: https://numpy.org/doc/stable/reference/generated/numpy.equal.html

```[[False, False, False],
  [False, False,  True],
  [False, False,  True]]```
  
Example output -- remember the array C is randomly generated so your result will be different

In [75]:
np.equal(B,C)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

###  11.18. In place, negate all elements in the array A which have a value greater than 6
Hint: https://numpy.org/doc/stable/reference/generated/numpy.where.html

```[ 1,  2,  3,  4,  5,  6, -7, -8, -9]```

In [153]:
np.where(A < 6, 2*A, -A)

array([ 2,  4,  6,  8, 10, -6, -7, -8, -9])

## Linear algebra

### 11.19. Find the dot product of the arrays B and C (real matrix multiplication)
Hint: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

```[[1, 2, 3],           [[3, 8, 4],             [[ 36,  23,  43]
  [4, 5, 6],     ·      [3, 0, 6],       =      [ 81,  62, 100],
  [7, 8, 9]]            [9, 5, 9]]              [126, 101, 157]]```

Example output -- remember the array C is randomly generated so your result will be different

In [82]:
np.dot(B,C)

array([[20, 29, 17],
       [53, 62, 53],
       [86, 95, 89]])

### 11.20. Find the determinant of the matrix B
Hint: https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html

```0.0```

In [147]:
np.linalg.det(B)

6.66133814775094e-16

### 11.21. Find the transpose of the matrix B
Hint: https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

```[[1, 4, 7],
  [2, 5, 8],
  [3, 6, 9]]```

In [149]:
np.transpose(B)
#B.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 11.22. Find the inverse of the matrix C (first check that its determinant is nonzero)
Hint: https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

```[[-0.16129032, -0.27956989,  0.25806452],
  [ 0.14516129, -0.0483871 , -0.03225806],
  [ 0.08064516,  0.30645161, -0.12903226]```
  
Example output -- remember the array C is randomly generated so your result will be different

In [90]:
if(np.linalg.det(C) != 0):
    print(np.linalg.inv(C))
else:
    print('Determinant = 0')

[[ 0.18181818 -3.18181818  0.77272727]
 [-0.09090909  1.09090909 -0.13636364]
 [ 0.          2.         -0.5       ]]


Bonus!! Find the seed of 11.7

In [123]:
true = np.array([[6, 5, 9],
  [0, 6, 3],
  [6, 4, 2]])

In [150]:
for i in range(1000000): #possible permutations = 1000000000, so this may or may not find a seed #takes a long time, for me takes 1000 minutes
    test = np.random.randint(10,size = (3,3))
    compare = test == true
    if(compare.all()):
        print(i)

In [126]:
test

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [127]:
true

array([[6, 5, 9],
       [0, 6, 3],
       [6, 4, 2]])

In [128]:
test == true

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])